CREATE TABLE IF NOT EXISTS Chatbeitrag (ID int NOT NULL AUTO_INCREMENT,NACHRICHT varchar(255) NOT NULL,BENUTZERNAME varchar(20),PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS Benutzer (BENUTZERNAME varchar(40) NOT NULL,PASSWORD varchar(20), EMAIL varchar(40), ROLLE varchar(40), INSERT_TIME DATE, GRUPPENNAME varchar(40), PRIMARY KEY (BENUTZERNAME));
CREATE TABLE IF NOT EXISTS Gruppe (GRUPPENNAME varchar(40) NOT NULL,INSERT_TIME DATE, PRIMARY KEY (GRUPPENNAME));
CREATE TABLE IF NOT EXISTS Beitrag (ID int NOT NULL AUTO_INCREMENT,BEITRAG_ERSTELLER varchar(20) NOT NULL,BEITRAG_INHALT varchar(255), BEITRAG_ERSTELLTAM DATE, THEMA_ID int NOT NULL, PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS Thema (THEMA_ID int NOT NULL AUTO_INCREMENT,THEMA_ERSTELLER varchar(20) NOT NULL,THEMA_INHALT varchar(255), ERSTELLT_AM DATE, PRIMARY KEY (THEMA_ID));
ALTER TABLE Beitrag ADD FOREIGN KEY (THEMA_ID) REFERENCES THEMA(THEMA_ID);
ALTER TABLE Benutzer ADD FOREIGN KEY (GRUPPENNAME) REFERENCES GRUPPE(GRUPPENNAME);