CREATE TABLE IF NOT EXISTS Chatbeitrag (ID int NOT NULL AUTO_INCREMENT,NACHRICHT varchar(255) NOT NULL,BENUTZERNAME varchar(20),PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS Benutzer (ID int NOT NULL AUTO_INCREMENT,BENUTZERNAME varchar(40),PASSWORD varchar(20), EMAIL varchar(40),INSERT_TIME DATE, PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS BenutzerRolle (BENUTZER_ROLLE_ID int NOT NULL AUTO_INCREMENT,BENUTZERNAME varchar(40),ROLLE varchar(45),PRIMARY KEY (BENUTZER_ROLLE_ID)); 
ALTER TABLE BenutzerRolle ADD FOREIGN KEY (BENUTZERNAME) REFERENCES Benutzer(BENUTZERNAME);